(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "auto-complete")
(depends-on "color-theme")
(depends-on "cucumber-goto-step")
(depends-on "enh-ruby-mode")
(depends-on "feature-mode")
(depends-on "grizzl")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "robe")
(depends-on "ruby-tools")
(depends-on "smartparens")